context:
  name: xvega-bindings
  version: 0.1.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 3c60b64587e8c0bdd57579724c875115d7b08efdb7948b3fc4907b3e39aeed31

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xvega >=0.1.0,<0.2

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: Bindings from xvega to xeus.
  homepage: https://github.com/jupyter-xeus/xvega-bindings
  documentation: https://xeus-sqlite.readthedocs.io/en/latest/xvega_magic.html

extra:
  recipe-maintainers:
  - DerThorsten
