context:
  name: xvega
  version: 0.1.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 5b8a42723176b1872dc3e2777c6f0b2be95fff8ad54ec1356b26b5af5b645965

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xproperty
  run:
  - xproperty

tests:
- script:
  - test -f $PREFIX/lib/libxvega.a
  - test -f $PREFIX/include/xvega/xvega.hpp

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xvega
  homepage: https://github.com/jupyter-xeus/xvega

extra:
  recipe-maintainers:
  - DerThorsten
